# Generated by Django 6.0.5 on 2026-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0004_job_scraped_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSearchQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keywords", models.CharField(blank=True, max_length=255, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                ("remote", models.BooleanField(null=True)),
                ("countries", models.JSONField(blank=True, null=True)),
                ("industries", models.JSONField(blank=True, null=True)),
                ("job_types", models.JSONField(blank=True, null=True)),
                ("urls", models.JSONField(blank=True, null=True)),
                ("raw_params", models.JSONField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("success", "Success"), ("failure", "Failure")], default="pending", max_length=20)),
                ("results_count", models.IntegerField(default=0)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
