# Generated by Django 6.0.5 on 2026-05-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_add_rawjob_and_job_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraperun',
            old_name='duplicates',
            new_name='duplicate_records',
        ),
        migrations.RenameField(
            model_name='scraperun',
            old_name='jobs_found',
            new_name='records_received',
        ),
        migrations.RenameField(
            model_name='scraperun',
            old_name='jobs_saved',
            new_name='records_rejected',
        ),
        migrations.RenameField(
            model_name='scraperun',
            old_name='jobs_updated',
            new_name='records_saved',
        ),
        migrations.AddField(
            model_name='job',
            name='canonical_company',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scraperun',
            name='records_updated',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='remote_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
