import type { TrackerItemData } from "@/components/tracker/TrackerItemCard";

export const PIPELINE_ITEMS: TrackerItemData[] = [
  {
    id: "t1",
    company: "Stripe",
    role: "Senior Frontend Engineer",
    stage: "Interviewing",
    stageDays: 4,
    lastInteraction: "Recruiter email · 2d ago",
    historicalVelocity: "Fast",
    responseProbability: 88,
    ghostRisk: "Low",
    resumeBranch: "feature/stripe-frontend",
    followUpIn: "Prep for system design",
    nextAction: "Review prep guide",
  },
  {
    id: "t2",
    company: "Acme Corp",
    role: "Staff Software Engineer",
    stage: "Applied",
    stageDays: 12,
    lastInteraction: "Application submitted",
    historicalVelocity: "Slow",
    responseProbability: 34,
    ghostRisk: "High",
    resumeBranch: "feature/staff-generalist",
    followUpIn: "Overdue — send follow-up",
    nextAction: "Draft follow-up",
  },
  {
    id: "t3",
    company: "Vercel",
    role: "Product Engineer",
    stage: "Applied",
    stageDays: 2,
    lastInteraction: "Application submitted",
    historicalVelocity: "Fast",
    responseProbability: 76,
    ghostRisk: "Low",
    resumeBranch: "feature/staff-generalist",
    followUpIn: "Wait 3 more days",
    nextAction: "No action yet",
  },
  {
    id: "t4",
    company: "Linear",
    role: "Frontend Developer",
    stage: "Offer",
    stageDays: 1,
    lastInteraction: "Offer letter received",
    historicalVelocity: "Average",
    responseProbability: 95,
    ghostRisk: "Low",
    resumeBranch: "feature/staff-generalist",
    followUpIn: "Respond within 48h",
    nextAction: "Compare offer",
  },
  {
    id: "t5",
    company: "Global Tech",
    role: "UI Engineer",
    stage: "Interviewing",
    stageDays: 9,
    lastInteraction: "Technical screen · 8d ago",
    historicalVelocity: "Average",
    responseProbability: 52,
    ghostRisk: "Medium",
    resumeBranch: "feature/stripe-frontend",
    followUpIn: "Nudge recruiter today",
    nextAction: "Send follow-up",
  },
  {
    id: "t6",
    company: "Nova Systems",
    role: "Platform Engineer",
    stage: "Ghosted",
    stageDays: 21,
    lastInteraction: "No reply after apply",
    historicalVelocity: "Slow",
    responseProbability: 12,
    ghostRisk: "High",
    resumeBranch: "feature/staff-generalist",
    followUpIn: "Low chance — archive?",
    nextAction: "Mark as ghosted",
  },
];

export const PIPELINE_COLUMNS = [
  { id: "Applied", label: "Applied", accent: "text-primary", bar: "bg-primary" },
  { id: "Interviewing", label: "Interviewing", accent: "text-intelligence", bar: "bg-intelligence" },
  { id: "Offer", label: "Offer", accent: "text-success", bar: "bg-success" },
  { id: "Ghosted", label: "Ghosted", accent: "text-text-tertiary", bar: "bg-text-tertiary" },
  { id: "Rejected", label: "Rejected", accent: "text-danger", bar: "bg-danger" },
] as const;
