# Generated by Django 6.0.5 on 2026-05-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scraperun_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='exported_to_sheets',
            field=models.BooleanField(default=False),
        ),
    ]
