# Generated by Django 6.0.5 on 2026-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_job_exported_to_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scraped_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
