# Generated by Django 6.0.5 on 2026-05-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0005_jobsearchquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(max_length=100)),
                ("raw_data", models.JSONField()),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="remote_type",
            field=models.CharField(choices=[("remote", "Remote"), ("hybrid", "Hybrid"), ("onsite", "Onsite"), ("unknown", "Unknown")], default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
