# Generated by Django 6.0.5 on 2026-05-21 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0008_scrapesource_job_expired_at_job_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_blob', models.JSONField(default=dict)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred_seniority', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_industry', models.CharField(blank=True, max_length=100, null=True)),
                ('github_connected', models.BooleanField(default=False)),
                ('linkedin_connected', models.BooleanField(default=False)),
                ('resume_parsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplacePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stealth_mode', models.BooleanField(default=False)),
                ('blocked_companies', models.JSONField(blank=True, default=list)),
                ('target_salary_min', models.IntegerField(blank=True, null=True)),
                ('target_role_types', models.JSONField(blank=True, default=list)),
                ('target_stages', models.JSONField(blank=True, default=list)),
                ('identity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_preferences', to='core.professionalidentity')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('target_role', models.CharField(blank=True, max_length=100, null=True)),
                ('content_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_variants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inferred_from', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('resume', 'Resume'), ('manual', 'Manual')], max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.professionalidentity')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('role_title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('discovered', 'Discovered'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('stalled', 'Stalled')], default='discovered', max_length=50)),
                ('stage_updated_at', models.DateTimeField(auto_now_add=True)),
                ('ats_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('interview', 'Interview')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracker_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.trackeritem')),
            ],
        ),
    ]
